# Generated by Django 5.1.1 on 2024-09-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('icono', models.ImageField(upload_to='iconos_alertas/')),
                ('tipo_alerta', models.CharField(choices=[('emergencia', 'Emergencia'), ('informacion', 'Información')], default='informacion', max_length=50)),
                ('imagenes', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id_comunicado', models.AutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(max_length=100)),
                ('avatar_entidad', models.ImageField(upload_to='avatars_entidad/')),
                ('texto_comunicado', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes_comunicados/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('compartido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('icono', models.ImageField(upload_to='iconos_emergencia/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateField()),
                ('hora_evento', models.TimeField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='eventos/')),
                ('favorito', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecoleccionBasura',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('icono', models.ImageField(upload_to='iconos_recoleccion/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioMunicipal',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo_servicio', models.CharField(choices=[('recoleccion_basura', 'Recolección de basura'), ('pago', 'Pago')], default='recoleccion_basura', max_length=50)),
                ('ubicacion', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=100)),
                ('icono', models.ImageField(upload_to='iconos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('administrador', 'Administrador')], default='usuario', max_length=20)),
            ],
        ),
    ]
